# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IOSVoiceRecorder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IOSVoiceRecorder
  react_path = '../node_modules/react-native'
  yoga_path = File.join(react_path, '/ReactCommon/yoga/yoga')

  pod 'React', :path => react_path, :subspecs => [
    'Core',
    'RCTText',
    'RCTImage',
    'RCTWebSocket', # needed for debugging
    'RCTNetwork'
  ]
  
end
